"use client";

import { Suspense, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { OutboxEntry, ResearcherProfile } from "@/lib/types";

function ComposeInner() {
  const params = useSearchParams();
  const researcherId = params.get("researcher") ?? "";

  const [researcher, setResearcher] = useState<ResearcherProfile | null>(null);
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [to, setTo] = useState("");
  const [generator, setGenerator] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [sent, setSent] = useState<OutboxEntry | null>(null);

  const generate = useCallback(async () => {
    if (!researcherId) return;
    setBusy(true);
    setError("");
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ researcherId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Draft generation failed");
      setResearcher(data.researcher);
      setSubject(data.draft.subject);
      setBody(data.draft.body);
      setGenerator(data.draft.generator);
      setTo(data.researcher.email ?? "");
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }, [researcherId]);

  useEffect(() => {
    const t = setTimeout(generate, 0);
    return () => clearTimeout(t);
  }, [generate]);

  async function send() {
    setBusy(true);
    setError("");
    try {
      const res = await fetch("/api/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ researcherId, subject, body, to }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Send failed");
      setSent(data.entry);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }

  if (!researcherId) {
    return (
      <p className="text-slate-600">
        No researcher selected — pick one from the{" "}
        <Link href="/researchers" className="text-indigo-600 underline">
          directory
        </Link>
        .
      </p>
    );
  }

  return (
    <div className="grid gap-8 lg:grid-cols-[320px_1fr]">
      <aside>
        <h1 className="text-2xl font-bold">Compose</h1>
        {researcher && (
          <div className="mt-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h3 className="font-semibold">{researcher.name}</h3>
            <p className="text-sm text-slate-600">{researcher.title}</p>
            <p className="mt-1 text-xs text-slate-500">
              {researcher.department}, {researcher.school}
            </p>
            <div className="mt-3 flex flex-wrap gap-1">
              {researcher.researchAreas.map((a) => (
                <span key={a} className="rounded bg-slate-100 px-2 py-0.5 text-xs text-slate-600">
                  {a}
                </span>
              ))}
            </div>
            {researcher.bio && <p className="mt-3 text-sm text-slate-600">{researcher.bio}</p>}
            <a
              href={researcher.website ?? researcher.sourceUrl}
              target="_blank"
              rel="noreferrer"
              className="mt-3 inline-block text-xs text-indigo-600 underline"
            >
              Profile source ↗
            </a>
          </div>
        )}
        {generator && (
          <p className="mt-3 text-xs text-slate-500">
            Draft generated by {generator === "nim" ? "NVIDIA NIM" : "the built-in template engine"} — edit freely
            before sending.
          </p>
        )}
      </aside>

      <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        {sent ? (
          <div className="py-12 text-center">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-2xl">
              ✓
            </div>
            <h2 className="mt-4 text-xl font-semibold">
              {sent.status === "sent" ? "Email sent!" : "Saved to outbox"}
            </h2>
            <p className="mt-2 text-sm text-slate-600">
              To {sent.to} via {sent.method}. {sent.detail}
            </p>
            <div className="mt-6 flex justify-center gap-4 text-sm font-medium">
              <Link href="/outbox" className="text-indigo-600 hover:underline">
                View outbox
              </Link>
              <Link href="/researchers" className="text-indigo-600 hover:underline">
                Email another researcher
              </Link>
            </div>
          </div>
        ) : (
          <>
            <label className="block text-sm">
              <span className="font-medium text-slate-700">To</span>
              <input
                value={to}
                onChange={(e) => setTo(e.target.value)}
                placeholder={researcher?.email ?? "researcher@university.edu (no published email — find one on their site)"}
                className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm"
              />
            </label>
            <label className="mt-4 block text-sm">
              <span className="font-medium text-slate-700">Subject</span>
              <input
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm"
              />
            </label>
            <label className="mt-4 block text-sm">
              <span className="font-medium text-slate-700">Body</span>
              <textarea
                value={body}
                onChange={(e) => setBody(e.target.value)}
                rows={16}
                className="mt-1 w-full rounded-md border border-slate-300 p-3 text-sm leading-relaxed"
              />
            </label>
            {error && <p className="mt-3 text-sm text-red-600">{error}</p>}
            <div className="mt-5 flex gap-3">
              <button
                onClick={send}
                disabled={busy || !subject || !body}
                className="rounded-md bg-indigo-600 px-5 py-2 font-medium text-white hover:bg-indigo-700 disabled:opacity-50"
              >
                {busy ? "Working…" : "Send email"}
              </button>
              <button
                onClick={generate}
                disabled={busy}
                className="rounded-md border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:border-indigo-400 disabled:opacity-50"
              >
                Regenerate draft
              </button>
            </div>
          </>
        )}
      </section>
    </div>
  );
}

export default function ComposePage() {
  return (
    <Suspense fallback={<p className="text-slate-500">Loading…</p>}>
      <ComposeInner />
    </Suspense>
  );
}
